# Generated by Django 5.2.6 on 2026-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_variationcategory_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0 = no discount)'),
        ),
        migrations.DeleteModel(
            name='RatingSubmission',
        ),
    ]
