# Generated by Django 5.2.6 on 2026-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_add_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='ChicCherry@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+8801701020304', max_length=30)),
                ('address', models.CharField(default='Sylhet, Bangladesh', max_length=200)),
                ('copy', models.CharField(default='© 2025 ChicCherry', max_length=200)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
