# Generated by Django 5.2.6 on 2026-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='show_amex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_paypal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_stripe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_visa',
            field=models.BooleanField(default=True),
        ),
    ]
