# Generated by Django 5.2.6 on 2026-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='header_email',
            field=models.EmailField(default='ChicCherry@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='header_phone',
            field=models.CharField(default='+8801701020304', max_length=30),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='logo_text',
            field=models.CharField(default='ChicCherry', max_length=100),
        ),
    ]
