# Generated by Django 5.2.6 on 2025-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_order_status_orderstatusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusupdate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
